# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u8bfe\u7a0b\u540d\u79f0', 'verbose_name_plural': '\u8bfe\u7a0b\u540d\u79f0'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='course/%Y/%m', verbose_name='\u5c01\u9762'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7ae0\u8282\u540d\u79f0'),
        ),
    ]
