# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1\u7801', 'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1\u7801'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='banner/Y/%m', verbose_name='\u8f6e\u64ad\u56fe'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(null=True, verbose_name='\u8f6e\u64ad\u8bbf\u95ee\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(max_length=10, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
